app/teams/models.py
from __future__ import annotations
import typing as t

from app.database import db

from sqlalchemy.orm import Mapped, mapped_column

# TBA Documentation: https://www.thebluealliance.com/apidocs/v3 

class Team(db.Model):
    
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column()

    # weather the team is using this system for scouting, use for login method?
    is_scouting: Mapped[bool] = mapped_column()

    def __init__(self, team_number: int, **kwargs) -> None:

        # check if team numbr can exist
        if team_number <= 0 or team_number > 9999:
            raise ValueError("Team number out of possible range")
        
        # attempt to make a request to TheBlueAlliance.com to pull team name from their db
        team_name = "[PLACEHOLDER]"

        super(Team, self).__init__(id = team_number, name=team_name, **kwargs)
    
    @classmethod
    def from_tba(cls, team_number: int) -> Team:
        """Creates a team object from a tba profile

        Args:
            team_number (int): The team number of the team

        Returns:
            Team: A team object with tba data
        """
        team = cls.__new__(Team)

        team.id = team_number

        return team
    

    def get_tba_profile(self) -> t.Optional[dict[str,t.Any]]:
        """Makes a request to TBA API and returns the 

        Returns:
            dict[str,t.Any]: The application/json response from tba as a dict
        """
        return {}
    

app/teams/__init__.py
from flask import Blueprint

teams = Blueprint("teams", __name__, url_prefix="/teams", template_folder="templates/")

from . import views

app/teams/views.py
from flask import render_template

from . import teams

from app.database import db, select
from app.frc_api import api

from .models import Team

@teams.route("/")
def team_list():
    teams = db.session.execute(select(Team)).fetchall()

    return render_template("team_list.html", teams = teams)


@teams.route("/view/<int:id>")
def view_team(id: int):

    team = Team(id)
    return render_template(
        "team.html",
        team = team
    )

@teams.route("/fetch/frc/<int:id>")
def fetch_frc_data(id: int):
    """Makes calls to FRC API seperate from client DOM to smooth out loading times

    Args:
        id (int): Team number, from URL

    Returns:
        api.Team: A Team object containing response data
    """
    
    frc_data: api.Team = api.Team(id)

    return render_template("fetch/frc_data.html", team = frc_data)

app/teams/templates/assets/team_table.html
{% from 'bootstrap5/utils.html' import render_icon %}

{% if teams|length > 0 %}
    <table class="table overflow-scroll" style="height: 1000px;">
        <thead>
            <th>Team #</th>
            <th>Team Name</th>
        </thead>
        <tbody>
            {% for team in teams %}
                <tr>
                    <td>{{ team.id }}</td>
                    <td>Placeholder</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="alert alert-info" role="alert">
        {{ render_icon('info-circle') }}
        There aren't any teams registered in our database at the moment,
        if you are not part of the development team please report this failure to 
        CORE 2062's scouting subteam
    </div>
{% endif %}

app/teams/templates/fetch/frc_data.html
<div>
    {# This span is used to set other information on the page from the original onload function #}
    <span class="visually-hidden" id="frc-api-team-name-short">{{ team.name_short }}</span>

    <table class="table">
        <tbody>
            {% for key, value in team.info.items() %}
                <tr class="overflow-hidden">
                    <td class="col-4">{{ key }}</td>
                    <td>
                        {% if value in [None, ""] %}
                            None
                        {% else %}
                            {{ value }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

app/teams/templates/team.html
{% extends 'layout.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>{{ team.id }}</h1>
                <h4 class="placeholder-glow" id="team-name">
                    <span class="placeholder col-8"></span>
                </h4>
                <hr class="col-4">
                
            </div>
            <div class="col-md-6 bg-primary-dark">
                <h4>Team API Data</h4>
                <hr class="col-4">
                <div class="accordion accordion" id="api-data">
                    <div class="accordion-item">
                        {# 
                            THE BLUE ALLIANCE INFORMATION
                         #}
                        <h2 class="accordion-header">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#tbaData" aria-expanded="true" aria-controls="tbaData">
                                The Blue Alliance
                            </button>
                        </h2>
                        <div id="tbaData" class="accordion-collapse collapse show" data-bs-parent="api-data">
                            <div class="accordion-body bg-body-tertiary">
                                <p>Data from The Blue Alliance is found here, start with placeholders or loading bars</p>
                            </div>
                        </div>
                    </div>

                    <div class="accordion-item">
                        {# 
                            FRC API INFORMATION
                         #}
                        <div class="accordion-header">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#frcData" aria-expanded="true" aria-controls="frcData">
                                FRC Data
                            </button>
                        </div>
                        <div id="frcData" class="accordion-collapse collapse show" data-bs-parent="api-data">
                            <div class="accordion-body bg-body-tertiary" id="frc-data-target">
                                <div class="d-flex justify-content-center">
                                    <div class="spinner-border" role="status">
                                      <span class="visually-hidden">Loading...</span>
                                    </div>
                                  </div>
                            </div>
                        </div>
                    </div>

                    <div class="accordion-item">
                        {# 
                            OTHER RELEVANT INFORMATION
                         #}
                        <div class="accordion-header">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#otherData" aria-expanded="false" aria-controls="frcData">
                                Other Data
                            </button>
                        </div>
                        <div id="otherData" class="accordion-collapse collapse" data-bs-parent="api-data">
                            <div class="accordion-body bg-body-tertiary">
                                <strong>Insert a rendered table containing site specific data here or something</strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        window.onload = function() {
            url_endpoint = "{{ url_for('teams.fetch_frc_data', id=team.id) }}"
            fetch(url_endpoint, {
                method: "GET"
            })
            .then(response => response.text())
            .then(html => {
                document.getElementById("frc-data-target").innerHTML = html;
                document.getElementById("team-name").innerHTML = document.getElementById("frc-api-team-name-short").innerHTML;
            })
            .then(error => conosle.error("FRC API Error: ", error))
        };
    </script>
{% endblock %}

app/teams/templates/team_list.html
{% extends 'split_view.html' %}

{% block title %}
    Teams list
{% endblock %}

{% block body_left %}
    <div>
        <h3>Teams List</h3>
        {% include 'assets/team_table.html' %}
    </div>
{% endblock %}

{% block body_right %}
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">
                WORDS
            </h1>
        </div>
    </div>
{% endblock %}